In [1]:
from readData import readData

In [2]:
afstanden_sql = "SQL/Afstanden.sql"
emissie_sql = "SQL/Emissies.sql"

In [3]:
afstanden_data = readData(afstanden_sql, geodata=False)
afstanden_data

c:\Users\jong\education\Breinstein\GrandFinaleOD\scripts\readData.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, conn)

,nic,bedrijf,centroid_bedrijf,bu_code,bu_naam,centroid_buurt,distance
0,21010,Sonneborn Refined Products BV (Amsterdam),b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x90\x87\x...,BU03639997,None,"b""@q\x00\x00\x01\x0c\xa2\xec\x1c\xf9'\t\x00Aa\...",14516.687900
1,21011,Rütgers Resins B.V.,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\xc0\xc8\x...,BU03639997,None,"b""@q\x00\x00\x01\x0c\xa2\xec\x1c\xf9'\t\x00Aa\...",21482.357479
2,21101,Albemarle Catalysts Company B.,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\xb0\\\xfe...,BU03639997,None,"b""@q\x00\x00\x01\x0c\xa2\xec\x1c\xf9'\t\x00Aa\...",7010.429145
3,21102,ICL FERTILIZERS EUROPE C.V.,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x80N\xfd@...,BU03639997,None,"b""@q\x00\x00\x01\x0c\xa2\xec\x1c\xf9'\t\x00Aa\...",11464.223568
4,21302,Abbott Healthcare Products BV (Weesp),b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\xc0\xf7\x...,BU03639997,None,"b""@q\x00\x00\x01\x0c\xa2\xec\x1c\xf9'\t\x00Aa\...",9638.118688
...,...,...,...,...,...,...,...
1274770,220188,Hoogheemraadschap Hollands Noorderkwartier RWZ...,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x00\n\xfc...,BU04798150,Middel,b'@q\x00\x00\x01\x0c\xf55D\xca\x9c\xb9\xfb@\xc...,50094.307605
1274771,220223,Hoogheemraadschap Hollands Noorderkwartier RWZ...,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x00\x1d\x...,BU04798150,Middel,b'@q\x00\x00\x01\x0c\xf55D\xca\x9c\xb9\xfb@\xc...,24161.085204
1274772,220243,RWZI Haarlem-Waarderpolder,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00@\xe7\xf9@...,BU04798150,Middel,b'@q\x00\x00\x01\x0c\xf55D\xca\x9c\xb9\xfb@\xc...,11744.316383
1274773,220451,Hoogheemraadschap Hollands Noorderkwartier RWZ...,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x80\xd8\x...,BU04798150,Middel,b'@q\x00\x00\x01\x0c\xf55D\xca\x9c\xb9\xfb@\xc...,37263.482916
1274774,220469,Hoogheemraadschap Hollands Noorderkwartier RWZ...,b'@q\x00\x00\x01\x0c\x00\x00\x00\x00\x00\x0f\x...,BU04798150,Middel,b'@q\x00\x00\x01\x0c\xf55D\xca\x9c\xb9\xfb@\xc...,7715.535856

In [6]:
emissies = readData(emissie_sql, geodata=False)
emissies

c:\Users\jong\education\Breinstein\GrandFinaleOD\scripts\readData.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, conn)

        bu_code                bu_naam  fijnstof_afstand  stikstof_afstand
0    BU03639997                   None       7254.586834      92513.628093
1    BU03639998                   None       8274.722445     139395.472665
2    BU03849997                   None       6657.982984     235224.541818
3    BU03940676        Aalsmeerderbrug      32999.149509     285100.096018
4    BU03634403  Aalsmeerwegbuurt Oost      42326.192652     376518.490906
..          ...                    ...               ...               ...
734  BU03940346        Zwanenburg Oost      56322.781159     517617.480056
735  BU03940343        Zwanenburg West      61098.890733     544714.587137
736  BU03940345    Zwanenburg Zuidoost      57490.732273     524272.889403
737  BU03940344    Zwanenburg Zuidwest      59089.573200     534978.362302
738  BU03637304            Zwarte Gouw      37030.045167     310597.054805

[739 rows x 4 columns]

In [9]:
import geopandas as gpd
buurten = gpd.read_file("../data/buurten_od.geojson")
buurten

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,geometry
0,BU03639997,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97300 52.37979, 4.97321 52.3..."
1,BU03639998,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97093 52.36452, 4.97087 52.3..."
2,BU03849997,,WK038499,GM0384,Diemen,"MULTIPOLYGON (((5.01604 52.34513, 5.01613 52.3..."
3,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2..."
4,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2..."
...,...,...,...,...,...,...
734,BU04798110,Westzanerpolder,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.75530 52.43979, 4.75708 52.4..."
735,BU04798120,Westzaan Zuid,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78966 52.44323, 4.79033 52.4..."
736,BU04798130,J.J. Allanbuurt,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78304 52.46163, 4.78481 52.4..."
737,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4..."
738,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4..."

In [10]:
emissies.rename(columns={"bu_code":"buurtcode"}, inplace=True)

In [11]:
buurten_emissies = buurten.merge(emissies, on="buurtcode")
buurten_emissies

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,geometry,bu_naam,fijnstof_afstand,stikstof_afstand
0,BU03639997,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97300 52.37979, 4.97321 52.3...",None,7254.586834,92513.628093
1,BU03639998,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97093 52.36452, 4.97087 52.3...",None,8274.722445,139395.472665
2,BU03849997,,WK038499,GM0384,Diemen,"MULTIPOLYGON (((5.01604 52.34513, 5.01613 52.3...",None,6657.982984,235224.541818
3,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",Centrum,32517.968929,280985.903048
4,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2...",Stommeer,31454.304974,272260.865240
...,...,...,...,...,...,...,...,...,...
734,BU04798110,Westzanerpolder,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.75530 52.43979, 4.75708 52.4...",Westzanerpolder,74162.919579,621059.239968
735,BU04798120,Westzaan Zuid,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78966 52.44323, 4.79033 52.4...",Westzaan Zuid,70862.045574,591961.741954
736,BU04798130,J.J. Allanbuurt,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78304 52.46163, 4.78481 52.4...",J.J. Allanbuurt,72136.681551,595196.209310
737,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4...",Westzaan Noord,71295.906505,576773.377539
738,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",Middel,69189.664248,564058.889827

In [12]:
buurten_emissies.fijnstof_afstand.min()

4235.518894121287

In [15]:
import numpy as np
list(np.linspace(buurten_emissies.fijnstof_afstand.min(), buurten_emissies.fijnstof_afstand.max(), num=10))

[4235.518894121287,
 24564.245441765688,
 44892.971989410085,
 65221.698537054486,
 85550.42508469889,
 105879.15163234329,
 126207.87817998769,
 146536.60472763208,
 166865.3312752765,
 187194.05782292088]

In [ ]:
buurten_emissies= buurten_emissies.drop(columns="bu_naam")

In [23]:

buurten_emissies.to_file("../data/buurten_od_emissies.geojson")

In [24]:
buurten_emissies

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,geometry,fijnstof_afstand,stikstof_afstand
0,BU03639997,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97300 52.37979, 4.97321 52.3...",7254.586834,92513.628093
1,BU03639998,,WK036399,GM0363,Amsterdam,"MULTIPOLYGON (((4.97093 52.36452, 4.97087 52.3...",8274.722445,139395.472665
2,BU03849997,,WK038499,GM0384,Diemen,"MULTIPOLYGON (((5.01604 52.34513, 5.01613 52.3...",6657.982984,235224.541818
3,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",32517.968929,280985.903048
4,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2...",31454.304974,272260.865240
...,...,...,...,...,...,...,...,...
734,BU04798110,Westzanerpolder,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.75530 52.43979, 4.75708 52.4...",74162.919579,621059.239968
735,BU04798120,Westzaan Zuid,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78966 52.44323, 4.79033 52.4...",70862.045574,591961.741954
736,BU04798130,J.J. Allanbuurt,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78304 52.46163, 4.78481 52.4...",72136.681551,595196.209310
737,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4...",71295.906505,576773.377539
738,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",69189.664248,564058.889827

In [25]:
gezondheidsdata = readData("SQL/gezondheids.sql", geodata=False)

c:\Users\jong\education\Breinstein\GrandFinaleOD\scripts\readData.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, conn)

In [26]:
gezondheidsdata

,regio,gm_naam,recs,gwb_code,ind_wbi,Aantal inwoners,Aantal laag opgeleiden,Aantal middelbaar opgeleiden,Aantal hoog opgeleiden,Gem gestandaardiseerd inkomen van huish
0,Centrum,Aalsmeer,Buurt,BU03580000,1,2785,530,720,690,"40,7"
1,Stommeer,Aalsmeer,Buurt,BU03580001,1,6540,1580,2070,1290,"36,3"
2,Hornmeer,Aalsmeer,Buurt,BU03580004,1,2530,520,890,390,"35,0"
3,Uiterweg,Aalsmeer,Buurt,BU03580005,1,865,140,330,200,"66,7"
4,Kudelstaart,Aalsmeer,Buurt,BU03580100,1,9270,1960,3160,1890,"37,7"
...,...,...,...,...,...,...,...,...,...,...
731,Westzanerpolder,Zaanstad,Buurt,BU04798110,1,285,150,130,20,.
732,Westzaan Zuid,Zaanstad,Buurt,BU04798120,1,1425,210,620,280,"36,1"
733,J.J. Allanbuurt,Zaanstad,Buurt,BU04798130,1,650,120,220,190,"43,0"
734,Westzaan Noord,Zaanstad,Buurt,BU04798140,1,2415,410,870,580,"35,9"
735,Middel,Zaanstad,Buurt,BU04798150,1,95,10,40,30,.

In [28]:
gezondheidsdata.rename(columns={"gwb_code": "buurtcode"}, inplace=True)

In [30]:
buurten_emissies_gezondheid = buurten_emissies.merge(gezondheidsdata, on="buurtcode")
buurten_emissies_gezondheid

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,geometry,fijnstof_afstand,stikstof_afstand,regio,gm_naam,recs,ind_wbi,Aantal inwoners,Aantal laag opgeleiden,Aantal middelbaar opgeleiden,Aantal hoog opgeleiden,Gem gestandaardiseerd inkomen van huish
0,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",32517.968929,280985.903048,Centrum,Aalsmeer,Buurt,1,2785,530,720,690,"40,7"
1,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2...",31454.304974,272260.865240,Stommeer,Aalsmeer,Buurt,1,6540,1580,2070,1290,"36,3"
2,BU03580004,Hornmeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.78953 52.26785, 4.78965 52.2...",30335.389747,262808.440398,Hornmeer,Aalsmeer,Buurt,1,2530,520,890,390,"35,0"
3,BU03580005,Uiterweg,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.74420 52.26939, 4.74536 52.2...",30288.592185,260515.947299,Uiterweg,Aalsmeer,Buurt,1,865,140,330,200,"66,7"
4,BU03580100,Kudelstaart,WK035801,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75664 52.25127, 4.75683 52.2...",28641.254299,246817.714558,Kudelstaart,Aalsmeer,Buurt,1,9270,1960,3160,1890,"37,7"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,BU04798110,Westzanerpolder,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.75530 52.43979, 4.75708 52.4...",74162.919579,621059.239968,Westzanerpolder,Zaanstad,Buurt,1,285,150,130,20,.
732,BU04798120,Westzaan Zuid,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78966 52.44323, 4.79033 52.4...",70862.045574,591961.741954,Westzaan Zuid,Zaanstad,Buurt,1,1425,210,620,280,"36,1"
733,BU04798130,J.J. Allanbuurt,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78304 52.46163, 4.78481 52.4...",72136.681551,595196.209310,J.J. Allanbuurt,Zaanstad,Buurt,1,650,120,220,190,"43,0"
734,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4...",71295.906505,576773.377539,Westzaan Noord,Zaanstad,Buurt,1,2415,410,870,580,"35,9"
735,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",69189.664248,564058.889827,Middel,Zaanstad,Buurt,1,95,10,40,30,.

In [31]:
buurten_emissies_gezondheid.to_file("buurten_emissies_gezondheid.geojson")

In [37]:
gezondheids_data = readData("SQL/gezondheids_data.sql", geodata=False)
gezondheids_data

c:\Users\jong\education\Breinstein\GrandFinaleOD\scripts\readData.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql(query, conn)

        bu_code 18 jaar of ouder 18 - 65 jaar 65 jaar of ouder
0    BU03580000             81.4         87.0             67.7
1    BU03580001             80.3         84.3             69.2
2    BU03580004             79.4         84.3             70.1
3    BU03580005             84.2         87.4             75.3
4    BU03580100             82.2         85.2             71.6
..          ...              ...          ...              ...
731  BU04798110             83.7         84.9                .
732  BU04798120             82.3         85.4             68.1
733  BU04798130             84.2         87.9             73.5
734  BU04798140             79.8         84.4             69.5
735  BU04798150             84.4         87.3             74.8

[736 rows x 4 columns]

In [38]:
gezondheids_data.rename(columns={"bu_code": "buurtcode"}, inplace=True)

In [39]:
buurten_emissies_gezondheid = buurten_emissies_gezondheid.merge(gezondheids_data, on="buurtcode")
buurten_emissies_gezondheid

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,geometry,fijnstof_afstand,stikstof_afstand,regio,gm_naam,...,Aantal inwoners,Aantal laag opgeleiden,Aantal middelbaar opgeleiden,Aantal hoog opgeleiden,Gem gestandaardiseerd inkomen van huish,leeftijd_cat,ErvarenGezondheidGoedZeerGoed_4,18 jaar of ouder,18 - 65 jaar,65 jaar of ouder
0,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",32517.968929,280985.903048,Centrum,Aalsmeer,...,2785,530,720,690,"40,7",18 - 65 jaar,87.0,81.4,87.0,67.7
1,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",32517.968929,280985.903048,Centrum,Aalsmeer,...,2785,530,720,690,"40,7",18 jaar of ouder,81.4,81.4,87.0,67.7
2,BU03580000,Centrum,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.75718 52.27399, 4.75718 52.2...",32517.968929,280985.903048,Centrum,Aalsmeer,...,2785,530,720,690,"40,7",65 jaar of ouder,67.7,81.4,87.0,67.7
3,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2...",31454.304974,272260.865240,Stommeer,Aalsmeer,...,6540,1580,2070,1290,"36,3",18 - 65 jaar,84.3,80.3,84.3,69.2
4,BU03580001,Stommeer,WK035800,GM0358,Aalsmeer,"MULTIPOLYGON (((4.76498 52.27179, 4.76508 52.2...",31454.304974,272260.865240,Stommeer,Aalsmeer,...,6540,1580,2070,1290,"36,3",18 jaar of ouder,80.3,80.3,84.3,69.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2203,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4...",71295.906505,576773.377539,Westzaan Noord,Zaanstad,...,2415,410,870,580,"35,9",18 jaar of ouder,79.8,79.8,84.4,69.5
2204,BU04798140,Westzaan Noord,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.77577 52.47264, 4.77748 52.4...",71295.906505,576773.377539,Westzaan Noord,Zaanstad,...,2415,410,870,580,"35,9",65 jaar of ouder,69.5,79.8,84.4,69.5
2205,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",69189.664248,564058.889827,Middel,Zaanstad,...,95,10,40,30,.,18 - 65 jaar,87.3,84.4,87.3,74.8
2206,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",69189.664248,564058.889827,Middel,Zaanstad,...,95,10,40,30,.,18 jaar of ouder,84.4,84.4,87.3,74.8
2207,BU04798150,Middel,WK047981,GM0479,Zaanstad,"MULTIPOLYGON (((4.78167 52.48682, 4.78223 52.4...",69189.664248,564058.889827,Middel,Zaanstad,...,95,10,40,30,.,65 jaar of ouder,74.8,84.4,87.3,74.8

In [40]:
buurten_emissies_gezondheid.to_file("buurten_emissies_gezondheid.geojson")